export const ADD_FOLDER = "ADD_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const SELECT_FOLDER  = "SELECT_FOLDER";
export const EDIT_FOLDER_NAME = "EDIT_FOLDER_NAME";
export const SAVE_FOLDER_NAME = "SAVE_FOLDER_NAME";
export const TOGGLE_FOLDER_VIEW = "TOGGLE_FOLDER_VIEW";