export const ADD_TEST_CASE = "ADD_TEST_CASE";
export const REMOVE_TEST_CASE = "REMOVE_TEST_CASE";
export const RUN_TEST_CASE = "RUN_TEST_CASE";
export const RUN_TEST_CASE_COMPLETE = "RUN_TEST_CASE_COMPLETE";
export const RUN_ALL_TEST_CASES  = "RUN_ALL_TEST_CASES";
export const EDIT_TEST_CASE_NAME = "EDIT_TEST_CASE_NAME";
export const SAVE_TEST_CASE_NAME = "SAVE_TEST_CASE_NAME";

